apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-secret-reader
  namespace: user1
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-secret-binding
  namespace: user1  # user1 네임스페이스에서 적용
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: argo  # argo 네임스페이스에 있는 Argo ServiceAccount를 지정
roleRef:
  kind: Role
  name: argo-secret-reader
  apiGroup: rbac.authorization.k8s.io
